# Generated by Django 3.0.8 on 2020-07-18 20:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import emeraldpm.packages.fields
import emeraldpm.packages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField(max_length=4096)),
                ('repository_url', models.URLField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', emeraldpm.packages.fields.VersionNumberField(default=emeraldpm.packages.models.version_default)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('archive', models.FileField(upload_to=emeraldpm.packages.models.file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.Package')),
            ],
            options={
                'unique_together': {('version', 'package')},
            },
        ),
    ]
