# Generated by Django 3.0.8 on 2020-07-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('count', models.BigIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_counts', to='packages.Package')),
            ],
        ),
        migrations.AddIndex(
            model_name='downloadcount',
            index=models.Index(fields=['day'], name='packages_do_day_087b90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='downloadcount',
            unique_together={('day', 'package')},
        ),
    ]
