# Generated by Django 3.0.8 on 2020-07-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20200718_2210'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['package'], name='packages_ve_package_234bd2_idx'),
        ),
    ]
