# Generated by Django 3.0.8 on 2020-07-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20200718_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'get_latest_by': 'published'},
        ),
        migrations.AddField(
            model_name='version',
            name='readme',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
