# Generated by Django 3.0.8 on 2020-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20200720_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='repository_url',
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
    ]
