# Generated by Django 3.0.8 on 2020-07-20 20:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20200720_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
