# Generated by Django 3.0.8 on 2020-07-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20200720_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'get_latest_by': 'published', 'ordering': ['version']},
        ),
        migrations.AddField(
            model_name='version',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependents', to='packages.Version'),
        ),
    ]
